---
name: Docker image digests update

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  image-update:
    name: Docker image digests update
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Docker image digests
        uses: chainguard-dev/digestabot@v1.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
...
