---
name: Publish PyPi package when a new tag is pushed

on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - 'v*'

# https://docs.pypi.org/trusted-publishers/using-a-publisher/
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment: pypi-publish
    permissions:
      id-token: write
    steps:
      # https://github.com/pypa/sampleproject/blob/main/.github/workflows/release.yml
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"
          enable-cache: true
          cache-dependency-glob: ./pyproject.toml

      - name: Setup venv
        run: |
          uv venv
          echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV
          echo "$PWD/.venv/bin" >> $GITHUB_PAT

      - name: Install build dependencies
        run: uv pip install -U setuptools wheel build

      - name: Build
        run: uv build .

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
...
