---
name: Run Tox

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: Checkout source
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          fetch-depth: 0

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y prometheus

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true

      - name: Install python dependencies
        run: pip install .[test]

      - name: Run tox
        run: tox -e py

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354  # v6.0.1
        with:
          token: "${{secrets.CODECOV_TOKEN}}"
          # disable until codecov improves stability
          # fail_ci_if_error: true
          files: ./src/coverage.xml
...
